# Generated by Django 5.0.1 on 2024-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='image1',
            field=models.ImageField(blank=True, default='static/images/images1.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='image2',
            field=models.ImageField(blank=True, default='static/images/images1.jpeg', null=True, upload_to=''),
        ),
    ]
